// Generated by scripts/make-ambience.mjs. Do not edit by hand.
// Field recordings from Wikimedia Commons, trimmed, softened and looped for Emberwise.

export interface AmbienceCredit {
  id: string;
  title: string;
  author: string;
  license: string;
  licenseUrl: string;
  url: string;
  /** Loop length in samples at 48 kHz. */
  samples: number;
}

export const AMBIENCE_CREDITS: AmbienceCredit[] = [
  {
    "id": "rain",
    "title": "Garden rainfall",
    "author": "Lionel Allorge",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "url": "https://commons.wikimedia.org/wiki/File:Garden_rainfall.ogg",
    "samples": 2304000
  },
  {
    "id": "storm",
    "title": "Light Rain Distant Thunder July 5th 2016",
    "author": "https://freesound.org/people/kvgarlic/",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "url": "https://commons.wikimedia.org/wiki/File:Light_Rain_Distant_Thunder_July_5th_2016.wav",
    "samples": 4608000
  },
  {
    "id": "waves",
    "title": "Ocean Waves on a Tropical Beach",
    "author": "Jarrod stanley",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "url": "https://commons.wikimedia.org/wiki/File:Ocean_Waves_on_a_Tropical_Beach.ogg",
    "samples": 3456000
  },
  {
    "id": "wind",
    "title": "Wind in Swedish pine forest at 25 mps",
    "author": "W.carter",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "url": "https://commons.wikimedia.org/wiki/File:Wind_in_Swedish_pine_forest_at_25_mps.ogg",
    "samples": 2496000
  },
  {
    "id": "forest",
    "title": "Réveil des oiseaux",
    "author": "Joseph Sardin",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "url": "https://commons.wikimedia.org/wiki/File:R%C3%A9veil_des_oiseaux.ogg",
    "samples": 3455064
  },
  {
    "id": "stream",
    "title": "Water on Rocks",
    "author": "Dsw4",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Water_on_Rocks.ogg",
    "samples": 3168000
  },
  {
    "id": "night",
    "title": "Nightingale wind crickets - cut",
    "author": "Serg Childed",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "url": "https://commons.wikimedia.org/wiki/File:Nightingale_wind_crickets_-_cut.ogg",
    "samples": 3167047
  },
  {
    "id": "cafe",
    "title": "Cafe ambiance",
    "author": "Marble Toast",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "url": "https://commons.wikimedia.org/wiki/File:Cafe_ambiance.ogg",
    "samples": 3456000
  },
  {
    "id": "library",
    "title": "20121112 TU Delft Library, quiet study room - general ambience - SoundCloud - el mar",
    "author": "el_mar",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "url": "https://commons.wikimedia.org/wiki/File:20121112_TU_Delft_Library,_quiet_study_room_-_general_ambience_-_SoundCloud_-_el_mar.ogg",
    "samples": 3168000
  },
  {
    "id": "fire",
    "title": "Campfire sound ambience",
    "author": "Glaneur de sons",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Campfire_sound_ambience.ogg",
    "samples": 1728000
  },
  {
    "id": "train",
    "title": "Complete train ride 4 minutes",
    "author": "stephan",
    "license": "Public domain",
    "licenseUrl": "",
    "url": "https://commons.wikimedia.org/wiki/File:Complete_train_ride_4_minutes.ogg",
    "samples": 3360000
  }
];
