// Words for the road: original lines written for Emberwise, in Turkish and English.
// Each entry is [tr, en]; ids are "<tag>:<index>", so keep the order stable and add new lines at the end.
// {name} becomes the hero's name (and disappears gracefully when there is none).

export type QuoteTag =
  | 'life'
  | 'morning'
  | 'afternoon'
  | 'evening'
  | 'night'
  | 'task'
  | 'epic'
  | 'focus'
  | 'break'
  | 'level'
  | 'streak'
  | 'login'
  | 'comeback'
  | 'allDone'
  | 'goal'
  | 'low'
  | 'high';

type Pair = [string, string];

export const QUOTES: Record<QuoteTag, Pair[]> = {
  life: [
    ['Bugün de bir şeyler öğrendin; hayat zaten tam olarak bu.', 'You learned something today; that is what life is made of.'],
    ['Kendine, en sevdiğin arkadaşına davrandığın kadar nazik davran.', 'Be as kind to yourself as you are to your favourite friend.'],
    ['Yavaş ilerlemek de ilerlemektir.', 'Moving slowly is still moving.'],
    ['Mükemmel olmak zorunda değilsin; burada olman yeterli.', 'You don’t have to be perfect; being here is enough.'],
    ['Küçük bir gülümseme, bir günün yönünü değiştirebilir.', 'A small smile can change the direction of a day.'],
    ['Bazen en büyük cesaret, yarın yeniden denemektir.', 'Sometimes the bravest thing is trying again tomorrow.'],
    ['Kalbine iyi gelen şeylere daha çok yer aç.', 'Make more room for the things that feel good to your heart.'],
    ['Bugün yorgunsan, dinlenmek de işin bir parçası.', 'If you’re tired today, rest is part of the work too.'],
    ['Hayatın anlamı bazen büyük cevaplarda değil, sıcak bir çayın buharında saklıdır.', 'Sometimes the meaning of life hides not in big answers but in the steam of a warm cup of tea.'],
    ['Sen, sandığından çok daha fazlasını taşıyorsun. Bunu fark et.', 'You carry far more than you think. Notice that.'],
    ['Her yeni gün temiz bir sayfa ve kalem senin elinde.', 'Every new day is a clean page, and you hold the pen.'],
    ['Başkalarıyla değil, dünkü hâlinle yarış.', 'Don’t race others; race who you were yesterday.'],
    ['İyi ki varsın. Bunu bugün kimse söylemediyse, ben söyleyeyim.', 'I’m glad you exist. If no one said it today, let me.'],
    ['Hata yapmak, denediğinin kanıtıdır.', 'Making mistakes is proof that you tried.'],
    ['Dünyayı güzelleştirmek için büyük adımlar gerekmez; bir teşekkür bile yeter.', 'You don’t need big steps to make the world better; a thank-you is enough.'],
    ['Nefes al. Şu an, sahip olduğun tek zaman ve gayet güzel.', 'Breathe. This moment is the only time you have, and it’s a good one.'],
    ['Bazı günler sadece ayakta kalmak bile bir başarıdır.', 'Some days, simply getting through is an achievement.'],
    ['Merak, insanı her yaşta genç tutar.', 'Curiosity keeps you young at any age.'],
    ['Sevdiğin insanlara onları sevdiğini söylemek için yarını bekleme.', 'Don’t wait for tomorrow to tell people you love them.'],
    ['Kendi hızında yürü; çiçekler de aynı anda açmaz.', 'Walk at your own pace; flowers don’t all bloom at once.'],
    ['Gökyüzüne bakmayı unutma; hep oradadır ve hep güzeldir.', 'Don’t forget to look at the sky; it is always there and always beautiful.'],
    ['İçindeki ışık, karanlık günlerde de sönmez.', 'Your inner light doesn’t go out on dark days.'],
    ['Bugün kendine yaptığın küçük bir iyilik, yarın büyük bir güce dönüşür.', 'A small kindness to yourself today becomes great strength tomorrow.'],
    ['Hayat bir yarış değil, bir yolculuk. Manzaranın tadını çıkar.', 'Life isn’t a race, it’s a journey. Enjoy the view.'],
    ['Zor zamanlar geçer; sen kalırsın, hem de daha güçlü.', 'Hard times pass; you stay, and stronger.'],
    ['Gülmek için bahane arama, sebep yarat.', 'Don’t look for an excuse to laugh; make a reason.'],
    ['Birine yardım ettiğinde, aslında kendi kalbini de büyütürsün.', 'When you help someone, you grow your own heart too.'],
    ['Değerin, bugün yaptığın işlerin sayısıyla ölçülmez.', 'Your worth isn’t measured by how much you did today.'],
    ['Sabır, sessizce açan bir çiçek gibidir.', 'Patience is a flower that blooms quietly.'],
    ['Bazen “hayır” demek, kendine “evet” demektir.', 'Sometimes saying no is saying yes to yourself.'],
    ['Dünyada senin gibi biri daha yok. Bu bir tesadüf değil.', 'There’s no one else in the world quite like you. That’s no accident.'],
    ['Mutluluk bir varış noktası değil, yol boyunca toplanan küçük anlardır.', 'Happiness isn’t a destination; it’s small moments gathered along the way.'],
    ['Kendine bugün “aferin” dedin mi? Bence hak ettin.', 'Did you tell yourself “well done” today? I think you earned it.'],
    ['En güzel manzaralar genellikle zorlu yokuşların sonunda bekler.', 'The best views usually wait at the top of hard climbs.'],
    ['Geçmişi değiştiremezsin ama ondan öğrendiklerinle geleceği güzelleştirebilirsin.', 'You can’t change the past, but what it taught you can brighten the future.'],
    ['Bir kitap, bir şarkı, bir yürüyüş… Ruhunu besleyen şeyleri ihmal etme.', 'A book, a song, a walk… Don’t neglect what feeds your soul.'],
    ['Her şeyi bugün çözmek zorunda değilsin.', 'You don’t have to solve everything today.'],
    ['Kendine inanmak, yolun yarısını geçmektir.', 'Believing in yourself is getting halfway there.'],
    ['Hayallerin, onları taşıyacak kadar güçlü bir yüreğe emanet.', 'Your dreams are in the care of a heart strong enough to carry them.'],
    ['Bugün biri sana gülümsediyse, sen de birine gülümse. İyilik bulaşıcıdır.', 'If someone smiled at you today, smile at someone. Kindness is contagious.'],
    ['Yağmur da güneş kadar gereklidir; ikisi birlikte gökkuşağı yapar.', 'Rain is as necessary as sunshine; together they make rainbows.'],
    ['Duyguların geçici misafirlerdir; ağırla, sonra yolcu et.', 'Feelings are passing guests; welcome them, then see them off.'],
    ['Yeterince iyisin. Hem de şu hâlinle.', 'You’re good enough. Exactly as you are.'],
    ['Başlamak için hazır hissetmeyi bekleme; başladıkça hazır olursun.', 'Don’t wait to feel ready; you get ready by starting.'],
    ['İnsanı zengin eden, sahip oldukları değil, şükrettikleridir.', 'What makes us rich isn’t what we own, but what we’re grateful for.'],
    ['Kendini başkalarının gözünden değil, kendi kalbinden tanı.', 'Know yourself through your own heart, not other people’s eyes.'],
    ['Biraz ara vermek, vazgeçmek demek değildir.', 'Taking a pause isn’t giving up.'],
    ['Bugün dünyaya küçük bir iz bırak: bir not, bir iyilik, bir tebessüm.', 'Leave a small mark on the world today: a note, a kindness, a smile.'],
    ['Gerçek güç, nazik kalabilmektir.', 'True strength is staying gentle.'],
    ['Adımların küçük olabilir ama yönün doğruysa her biri değerli.', 'Your steps may be small, but if the direction is right, each one counts.'],
    ['Kendinle konuşurken sesinin tonuna dikkat et; seni en çok dinleyen sensin.', 'Mind your tone when you talk to yourself; you are your own closest listener.'],
    ['Bugün bir şeyi ilk kez dene. Hayat tazelik sever.', 'Try something for the first time today. Life loves freshness.'],
    ['Sevgi, verdikçe çoğalan tek hazinedir.', 'Love is the only treasure that grows as you give it away.'],
    ['Doğada geçen beş dakika, zihninde saatlerce süren bir sessizlik bırakır.', 'Five minutes in nature leaves hours of quiet in your mind.'],
    ['İyi ki denedin. Sonuç ne olursa olsun.', 'Glad you tried. Whatever the result.'],
    ['Hayat bazen planlarını bozar ki sana daha güzel bir yol göstersin.', 'Sometimes life breaks your plans to show you a lovelier path.'],
    ['Kendi masalının kahramanı sensin; yan karakter olmayı kabul etme.', 'You’re the hero of your own tale; don’t settle for a side role.'],
    ['Dinlenmiş bir zihin, en parlak fikirlerin yuvasıdır.', 'A rested mind is home to the brightest ideas.'],
    ['Kalbin hafif olsun; taşımana gerek olmayan yükleri bırak.', 'Let your heart be light; put down what you don’t need to carry.'],
    ['Küçük şeylerin tadını çıkar: ilk yudum kahve, temiz çarşaf, sevilen bir şarkı.', 'Savour the small things: the first sip of coffee, clean sheets, a favourite song.'],
    ['Kimse her şeyi bilmez; öğrenmeye açık olmak bir süper güçtür.', 'Nobody knows everything; being open to learning is a superpower.'],
    ['Bugün kendine bir mektup yazsan ne derdin? Belki de duymaya ihtiyacın olan budur.', 'If you wrote yourself a letter today, what would it say? Maybe that’s what you need to hear.'],
    ['Güneş her sabah yeniden doğar; sen de doğabilirsin.', 'The sun rises again every morning; so can you.'],
    ['Anı yaşamak geleceği ihmal etmek değil, bugünü onurlandırmaktır.', 'Living in the moment isn’t neglecting the future; it’s honouring today.'],
    ['Hayallerin büyükse, adımların küçük olsa da olur.', 'If your dreams are big, small steps are fine.'],
    ['İnsanın değeri, zor günlerde koruduğu nezaketle görünür.', 'A person’s worth shows in the kindness they keep on hard days.'],
    ['Kendine zaman ayırmak bencillik değil, bakımdır.', 'Making time for yourself isn’t selfish; it’s care.'],
    ['En güzel hikâyeler, “bir kez daha deneyeyim” diyenlerin hikâyeleridir.', 'The best stories belong to those who said “let me try once more.”'],
    ['Ektiğin her tohum, bir gün gölgesinde dinleneceğin bir ağaca dönüşebilir.', 'Every seed you plant may one day become a tree you rest beneath.'],
    ['Hayat, cevaplardan çok güzel sorularla ilerler.', 'Life moves forward more on good questions than on answers.'],
    ['Bugün aynaya bak ve kendine teşekkür et; seni buraya kadar o taşıdı.', 'Look in the mirror today and thank yourself; that person carried you this far.'],
    ['Sessizlik de bir cevaptır; bazen en iyisi.', 'Silence is an answer too; sometimes the best one.'],
    ['Biri sana ihtiyaç duyduğunda orada olmak, dünyanın en güzel işlerinden biri.', 'Being there when someone needs you is one of the best jobs in the world.'],
    ['Endişe, yarının yükünü bugüne taşır; bırak yarın kendi yükünü taşısın.', 'Worry carries tomorrow’s load into today; let tomorrow carry its own.'],
    ['Küçük bir ilerleme, hiç ilerlememekten her zaman iyidir.', 'A little progress always beats none.'],
    ['Kendini affetmek, yeniden başlamanın kapısıdır.', 'Forgiving yourself is the door to starting again.'],
    ['Sevdiğin bir işi yaparken zaman uçar; o işleri çoğalt.', 'Time flies when you do what you love; do more of that.'],
    ['Bir pencere aç, temiz hava al; bazen değişim bu kadar basit başlar.', 'Open a window, breathe fresh air; sometimes change starts that simply.'],
    ['Hayat seni şaşırtmaya devam edecek. Merakını kaybetme.', 'Life will keep surprising you. Stay curious.'],
    ['Gerçek başarı, akşam başını yastığa huzurla koyabilmektir.', 'Real success is laying your head down at night in peace.'],
    ['Kendine karşı sabırlı ol; büyümek zaman alır.', 'Be patient with yourself; growing takes time.'],
    ['Bir gün herkes senin nezaketini, başarılarından daha iyi hatırlayacak.', 'One day people will remember your kindness better than your achievements.'],
    ['Bir ağaç gibisin: fırtınada eğilirsin ama kökün sağlam.', 'You’re like a tree: you bend in the storm, but your roots hold.'],
    ['Bugünün en güzel anı henüz gelmemiş olabilir.', 'The best moment of today may not have happened yet.'],
    ['İçinden geldiği gibi gül; ciddiyeti başka güne sakla.', 'Laugh freely; save seriousness for another day.'],
    ['Kendini başkalarıyla kıyaslamak, kendi şarkını duymamak demektir.', 'Comparing yourself to others means missing your own song.'],
    ['Bazen bir mola, bütün bir günü kurtarır.', 'Sometimes one break saves a whole day.'],
    ['Dünya iyi kalpli insanlarla güzel. Sen de onlardan birisin.', 'The world is lovely because of kind-hearted people. You’re one of them.'],
    ['Pes etmek istediğinde, ilk heyecanını hatırla.', 'When you want to quit, remember your first spark of excitement.'],
    ['Hayat kısa ama güzel anlarla uzun.', 'Life is short, but long in beautiful moments.'],
    ['Kimse seni senden daha iyi tanıyamaz; sesine güven.', 'No one knows you better than you; trust your voice.'],
    ['Her bitiş, yeni bir başlangıcın ilk sayfasıdır.', 'Every ending is the first page of a new beginning.'],
    ['İçtiğin su, uyuduğun saat, yürüdüğün adım… Hepsi kendine yaptığın bir yatırım.', 'The water you drink, the sleep you get, the steps you take… all of it is an investment in you.'],
    ['Zorluklar, karakterin heykeltıraşıdır.', 'Challenges are the sculptors of character.'],
    ['İçindeki çocuğu unutma; o hâlâ oyun oynamak istiyor.', 'Don’t forget the child inside you; they still want to play.'],
    ['Minnettarlık, sıradan bir günü bayrama çevirir.', 'Gratitude turns an ordinary day into a celebration.'],
    ['Biri seni anlamadığında kendini küçültme.', 'When someone doesn’t understand you, don’t make yourself smaller.'],
    ['Her gün, bir şeyi iyileştirmek için harika bir fırsat.', 'Every day is a fine chance to make one thing better.'],
    ['Kendine verdiğin sözleri tutmak, en derin özgüveni inşa eder.', 'Keeping promises to yourself builds the deepest confidence.'],
    ['Bulutlar ne kadar kalın olursa olsun, üstlerinde güneş hep parlıyor.', 'However thick the clouds, the sun is always shining above them.'],
    ['Hayatta en çok pişman olunanlar, denenmeyen şeylerdir.', 'The things we regret most are usually the ones we never tried.'],
    ['Sevgiyle yapılan her iş, sıradan olmaktan çıkar.', 'Anything done with love stops being ordinary.'],
    ['Yalnız hissettiğinde, aynı gökyüzünü paylaştığın milyarlarca insanı düşün.', 'When you feel alone, think of the billions sharing the same sky.'],
    ['Bir adım geri çekilmek, daha uzağa sıçramak için de olabilir.', 'Stepping back can be a way to leap further.'],
    ['Huzur, her şeyin yolunda gitmesi değil; her şeye rağmen sakin kalabilmektir.', 'Peace isn’t everything going right; it’s staying calm in spite of everything.'],
    ['Başkaları rahat etsin diye ışığını kısma; parla.', 'Don’t dim your light to make others comfortable; shine.'],
    ['Bugün güzel bir şey fark et ve onu birine anlat.', 'Notice something beautiful today and tell someone about it.'],
    ['Yaşadığın her şey, seni bugünkü güzel insana dönüştürdü.', 'Everything you’ve been through shaped the lovely person you are today.'],
    ['Kalbin bir bahçe; neyi sularsan o büyür.', 'Your heart is a garden; what you water grows.'],
    ['Yolunda kaybolmuş gibi hissetsen de, her adım seni bir yere götürüyor.', 'Even if you feel lost along the way, every step is taking you somewhere.'],
    ['Yeni bir alışkanlık, yeni bir sen demektir.', 'A new habit means a new you.'],
    ['Hayat, kahkahaları biriktirdiğin bir kumbara olsun.', 'Let life be a jar where you save up laughter.'],
    ['Bugün, dün hayalini kurduğun gün olabilir. Fark et.', 'Today might be the day you dreamed of yesterday. Notice it.'],
    ['Korktuğun hâlde bir adım atıyorsan, işte cesaret tam olarak bu.', 'If you’re scared and step forward anyway, that’s exactly what courage is.'],
    ['Sevdiğin birine bugün küçük bir mesaj at.', 'Send a little message to someone you love today.'],
    ['Hep aynı yoldan yürüme; bazen sokağın öbür tarafı yepyeni bir dünya.', 'Don’t always walk the same road; sometimes the other side of the street is a whole new world.'],
    ['Kendine iyi bak; bu dünyanın sana ihtiyacı var.', 'Take care of yourself; the world needs you.'],
    ['İçindeki sesi dinle; çoğu zaman haklıdır.', 'Listen to your inner voice; it’s right more often than not.'],
    ['Basit bir hayat, sade bir sevinç, derin bir nefes. Yeter de artar bile.', 'A simple life, a plain joy, a deep breath. Enough, and then some.'],
    ['Bugün kendinle gurur duyabileceğin bir şey yap, ne kadar küçük olursa olsun.', 'Do one thing you can be proud of today, however small.'],
    ['Bugüne bir gülümsemeyle başla; gün de sana gülümseyecek.', 'Start today with a smile; the day will smile back.'],
    ['Mevsimler değişir, sen de değişebilirsin. Bu bir güzellik.', 'Seasons change, and so can you. That’s a beautiful thing.'],
    ['Bir şeyi anlamak için bazen sadece biraz beklemek gerekir.', 'Sometimes understanding something just takes a little waiting.'],
    ['Kendine dürüst ol; en sağlam köprü odur.', 'Be honest with yourself; it’s the sturdiest bridge there is.'],
    ['Dünya senin gülüşünü görmeyi hak ediyor.', 'The world deserves to see you smile.'],
    ['Bugün yaşadığın en küçük güzel an bile, yarının hatırasıdır.', 'Even the smallest lovely moment today is tomorrow’s memory.'],
    ['Zor bir günden sonra kendine sıcak bir çorba ve erken bir uyku hediye et.', 'After a hard day, gift yourself warm soup and an early night.'],
    ['Gördüğün herkesin içinde görmediğin bir hikâye var; nazik olmak hep doğru seçim.', 'Everyone you see carries a story you can’t see; kindness is always the right choice.'],
    ['Planların değişebilir, hedefin aynı kalabilir.', 'Plans can change while the goal stays the same.'],
    ['Kendini sevmek, her şeyin başlangıcıdır.', 'Loving yourself is where everything begins.'],
    ['Bugünün tek bir görevi olsa bile, o şu olsun: kendine iyi davran.', 'If today has just one task, let it be this: be good to yourself.'],
    ['Kuşlar şarkı söylemek için mükemmel bir sabah beklemez.', 'Birds don’t wait for a perfect morning to sing.'],
    ['Bir fincan çay, bir pencere kenarı ve sen. Bazen dünya bu kadar güzel.', 'A cup of tea, a windowsill, and you. Sometimes the world is that lovely.'],
    ['Yorulduğunda dur ve dinlen; yol seni bekler.', 'When you’re tired, stop and rest; the road will wait for you.'],
    ['Seni mutlu eden şeylerin bir listesini yap ve ona sık sık bak.', 'Make a list of what makes you happy and look at it often.'],
    ['İyilik yapmak için izin beklemene gerek yok.', 'You don’t need permission to be kind.'],
    ['Bugün hissettiğin her şey geçerli; ama hepsi geçici.', 'Everything you feel today is valid, and all of it is temporary.'],
    ['Bir hayalin varsa, ona her gün küçük bir selam ver.', 'If you have a dream, give it a small hello every day.'],
    ['Sen bu dünyanın küçük ama vazgeçilmez bir parçasısın.', 'You’re a small but irreplaceable piece of this world.'],
    ['Gün biterken kendine sor: “Bugün neye güldüm?”', 'As the day ends, ask yourself: “What made me laugh today?”'],
  ],
  morning: [
    ['Günaydın {name}! Bugün sana iyi haberler getirecek bir gün.', 'Good morning, {name}! Today feels like a day of good news.'],
    ['Yeni bir sabah, yeni bir şans. Hadi bakalım!', 'A new morning, a new chance. Let’s go!'],
    ['Güne bir bardak suyla başla; vücudun sana teşekkür edecek.', 'Start the day with a glass of water; your body will thank you.'],
    ['Bugün sadece bir şeyi bitirsen bile harika bir gün olur.', 'Even if you finish just one thing today, it’ll be a great day.'],
    ['Sabahın ilk ışığı gibi sakin ve kararlı ol.', 'Be calm and steady, like the first light of morning.'],
    ['Kahven hazırsa, maceraya da hazırsın.', 'If your coffee is ready, so is your adventure.'],
    ['Güne kendine gülümseyerek başla. Gerisi kolay.', 'Start the day by smiling at yourself. The rest is easy.'],
    ['Bugün kendine güzel bir plan yap ve ona nazikçe sadık kal.', 'Make yourself a kind plan today and stick to it gently.'],
    ['Erken kalkan, güne biraz daha uzun sarılır. Tadını çıkar!', 'Early risers get to hug the day a little longer. Enjoy it!'],
    ['Sabahlar, dünün yorgunluğunu silen birer silgidir.', 'Mornings are erasers for yesterday’s tiredness.'],
    ['Bugün için tek bir niyet seç ve onu kalbinde taşı.', 'Choose one intention for today and carry it in your heart.'],
    ['Pencereyi aç, derin bir nefes al; gün seni bekliyor.', 'Open the window, take a deep breath; the day is waiting.'],
    ['Günaydın! Dünyanın senin enerjine ihtiyacı var.', 'Good morning! The world needs your energy.'],
    ['Günün ilk adımı en önemlisidir ve sen onu attın bile.', 'The first step of the day matters most, and you’ve already taken it.'],
    ['Bugün güzel bir şey olacak. Belki de onu sen yapacaksın.', 'Something good will happen today. Maybe you’ll be the one to do it.'],
    ['Sabah sessizliği, düşüncelerin en berrak hâlidir.', 'Morning quiet is when your thoughts are clearest.'],
    ['Bir esneme, bir gülümseme, bir plan. Hazırsın {name}.', 'A stretch, a smile, a plan. You’re ready, {name}.'],
    ['Dünkü sen, bugünkü sene güveniyor.', 'Yesterday’s you is counting on today’s you.'],
  ],
  afternoon: [
    ['Günün yarısı geride; şimdiye kadar yaptıkların için kendine teşekkür et.', 'Half the day is behind you; thank yourself for what you’ve done so far.'],
    ['Öğleden sonra yorgunluğu mu? Kısa bir yürüyüş mucizeler yaratır.', 'Afternoon slump? A short walk works wonders.'],
    ['Bir bardak su ve birkaç derin nefes: öğleden sonra yakıtın hazır.', 'A glass of water and a few deep breaths: your afternoon fuel is ready.'],
    ['Günün geri kalanı hâlâ senin. Ne yapmak istersin?', 'The rest of the day is still yours. What would you like to do with it?'],
    ['Yavaşladıysan sorun yok; öğleden sonraları zaten biraz yavaştır.', 'If you’ve slowed down, that’s okay; afternoons are a little slow anyway.'],
    ['Şimdi küçük bir görevle ivme kazanmanın tam zamanı.', 'Now’s a good time to build momentum with one small quest.'],
    ['Gün ortasında kendine bir “aferin” bırak.', 'Leave yourself a “well done” in the middle of the day.'],
    ['Güneş tepede, sen de zirvedesin.', 'The sun’s at its peak, and so are you.'],
    ['Öğle arası bitti ama güzel haberler bitmedi.', 'Lunch break’s over, but the good news isn’t.'],
    ['Bir sonraki saat için sadece tek bir şeye odaklan.', 'For the next hour, focus on just one thing.'],
    ['Omuzlarını gevşet, çeneni bırak; ne kadar gergin olduğunu fark ettin mi?', 'Relax your shoulders, unclench your jaw; did you notice how tense you were?'],
    ['Günün ikinci yarısı, yeni bir başlangıç gibi olabilir.', 'The second half of the day can be a fresh start.'],
  ],
  evening: [
    ['İyi akşamlar {name}. Bugün yeterince iyiydin.', 'Good evening, {name}. You did enough today.'],
    ['Akşamlar, günün yükünü bırakma zamanıdır.', 'Evenings are for setting down the day’s weight.'],
    ['Bugün neler başardığına bir bak; listeden fazlası var.', 'Look at what you accomplished today; it’s more than the list.'],
    ['Yarın için küçük bir plan yap, sonra zihnini dinlendir.', 'Make a small plan for tomorrow, then let your mind rest.'],
    ['Akşam ışığı her şeyi biraz daha yumuşak gösterir; sen de kendine yumuşak davran.', 'Evening light makes everything softer; be soft with yourself too.'],
    ['Bugün güzel olan üç şeyi düşün.', 'Think of three good things from today.'],
    ['Ekranları biraz kıs, kalbini biraz aç.', 'Dim the screens a little, open your heart a little.'],
    ['Sevdiklerinle geçen bir akşam, en verimli zamanlardan biridir.', 'An evening with loved ones is some of the best-spent time there is.'],
    ['Bitmeyen işler yarına kalabilir; sen de dinlenmeyi hak ediyorsun.', 'Unfinished work can wait until tomorrow; you deserve rest too.'],
    ['Günü güzel bir müzikle uğurla.', 'See the day off with some good music.'],
    ['Bugün kendine iyi davrandın mı? Henüz geç değil.', 'Were you kind to yourself today? It’s not too late.'],
    ['Akşamın sakinliği, yarının gücüdür.', 'The calm of the evening is tomorrow’s strength.'],
    ['Bir çay demle, ayaklarını uzat; bugün bitti ve sen harikaydın.', 'Brew some tea, put your feet up; today is done and you were great.'],
    ['Günün sonunda önemli olan, kendinle barışık olman.', 'At the end of the day, what matters is being at peace with yourself.'],
  ],
  night: [
    ['Geç oldu {name}; en iyi fikirler dinlenmiş zihinlerden çıkar.', 'It’s late, {name}; the best ideas come from rested minds.'],
    ['Uyku, yarının süper gücüdür.', 'Sleep is tomorrow’s superpower.'],
    ['Yıldızlar parlıyor, sen de bugün parladın. Şimdi dinlen.', 'The stars are shining, and you shone today too. Now rest.'],
    ['Gecenin sessizliğinde kendine teşekkür et.', 'In the quiet of the night, thank yourself.'],
    ['Yarın yeni bir gün; bugünü burada bırakabilirsin.', 'Tomorrow is a new day; you can leave today here.'],
    ['Dinlenmek vazgeçmek değil, yeniden dolmaktır.', 'Resting isn’t quitting; it’s refilling.'],
    ['Gece kuşu musun? Yine de birkaç saat uyku altından değerlidir.', 'Night owl? Still, a few hours of sleep are worth more than gold.'],
    ['Uyumadan önce telefonu bırak, bir sayfa kitap oku.', 'Put the phone down before bed and read one page of a book.'],
    ['Bugünün düşüncelerini bir kenara koy; sabah hepsi daha net olacak.', 'Set today’s thoughts aside; in the morning they’ll all be clearer.'],
    ['İyi geceler. Rüyaların sıcak ve tatlı olsun.', 'Good night. May your dreams be warm and sweet.'],
    ['Kor ruhu da uyuyor; sen de ona katıl.', 'Even the ember spirit is asleep; why not join it?'],
    ['Ay gökyüzünde nöbette; sen gönül rahatlığıyla dinlen.', 'The moon is keeping watch; rest easy.'],
  ],
  task: [
    ['Bir görev daha tamam! Böyle devam {name}.', 'Another quest done! Keep going, {name}.'],
    ['Adım adım, taş üstüne taş. Harika gidiyorsun.', 'Step by step, stone by stone. You’re doing great.'],
    ['İşte bu! Bitirmek, başlamaktan bile güzel.', 'That’s it! Finishing feels even better than starting.'],
    ['Bir şeyi bitirdin ve dünya biraz daha düzenli.', 'You finished something, and the world is a little tidier.'],
    ['Küçük zaferler büyük günleri inşa eder.', 'Small wins build big days.'],
    ['Listenden bir madde eksildi, kalbinden bir yük.', 'One item off your list, one weight off your heart.'],
    ['Gördün mü? Düşündüğünden daha kolaydı.', 'See? It was easier than you thought.'],
    ['Bu iş bitti. Şimdi kendine bir saniye gülümse.', 'That’s done. Now give yourself a second to smile.'],
    ['Kahramanın bugün biraz daha güçlendi.', 'Your hero got a little stronger today.'],
    ['Bir görevi bitirmenin tadı başka, değil mi?', 'Nothing quite like the taste of a finished quest, right?'],
    ['Disiplin, böyle küçük anların toplamıdır.', 'Discipline is the sum of little moments like this one.'],
    ['Harika iş! Bir sonrakine geçmeden su içmeyi unutma.', 'Great work! Have some water before the next one.'],
    ['Ertelemek yerine yaptın. Bu gerçek bir zafer.', 'You did it instead of putting it off. That’s a real win.'],
    ['Bitirdiğin her iş, gelecekteki sene bir hediye.', 'Every quest you finish is a gift to your future self.'],
    ['Ritmini buldun, şimdi akışa bırak.', 'You’ve found your rhythm; now go with the flow.'],
    ['Tık! Bu sesi seviyoruz.', 'Check! We love that sound.'],
    ['Görev tamam. Ateşin daha parlak yanıyor.', 'Quest complete. Your fire burns brighter.'],
    ['Böyle günler, alışkanlıkların doğduğu günlerdir.', 'Days like this are where habits are born.'],
    ['Bunu sen yaptın. Kimse elinden alamaz.', 'You did that. No one can take it from you.'],
    ['Bir görev bitti; bir nefes al, sonra devam.', 'One quest down; take a breath, then carry on.'],
    ['Kendine güvenin bir puan daha arttı.', 'Your trust in yourself just went up a notch.'],
    ['Bitirmek bir sanat ve sen bu işte ustalaşıyorsun.', 'Finishing is an art, and you’re mastering it.'],
    ['Bugünün listesi seninle gurur duyuyor.', 'Today’s list is proud of you.'],
    ['Ne güzel bir ilerleme! Yolun açık olsun.', 'What lovely progress! Clear roads ahead.'],
    ['Zor olanı yaptın; gerisi daha kolay gelecek.', 'You did the hard part; the rest will come easier.'],
    ['Her tamamlanan görev, “yapabilirim” demenin bir başka yolu.', 'Every finished quest is another way of saying “I can.”'],
    ['Odaklandın, uğraştın ve bitirdin. Mükemmel üçleme.', 'You focused, you worked, you finished. A perfect trio.'],
    ['Bu tempoyla bugün çok güzel bitecek.', 'At this pace, today will end beautifully.'],
    ['Sen bitirdikçe kor ruhu dans ediyor.', 'Every time you finish something, the ember spirit dances.'],
    ['Bir görev daha geride. Gelecekteki sen, şimdiki sene teşekkür ediyor.', 'Another one behind you. Future you says thank you.'],
  ],
  epic: [
    ['Destansı bir görevi devirdin! Bu gerçekten büyük bir iş.', 'You toppled an epic quest! That’s truly big.'],
    ['Zor olanı seçtin ve kazandın. Cesaretine hayranım.', 'You chose the hard one and won. I admire your courage.'],
    ['Dağın zirvesindesin {name}. Manzaranın tadını çıkar.', 'You’re at the summit, {name}. Enjoy the view.'],
    ['Bu görev seni korkutmuş olabilir ama sen ondan güçlü çıktın.', 'This quest may have scared you, but you came out stronger.'],
    ['Büyük işler, böyle cesur adımlarla biter.', 'Big things get done with brave steps like this.'],
    ['Bugün kendi efsaneni yazdın.', 'Today you wrote your own legend.'],
    ['İşte zorluklarla dans etmek böyle bir şey!', 'That’s what dancing with challenges looks like!'],
    ['Bu zaferi bir süre hatırla; zor anlarda işe yarar.', 'Remember this win for a while; it helps on hard days.'],
    ['Zor görevler, en güzel hikâyeleri bırakır.', 'Hard quests leave the best stories.'],
    ['Kendine bir ödül ver; bunu fazlasıyla hak ettin.', 'Give yourself a treat; you more than earned it.'],
  ],
  focus: [
    ['Bir odak seansı daha! Zihnin keskin bir kılıç gibi {name}.', 'Another focus session! Your mind is sharp as a blade, {name}.'],
    ['Derin çalıştın; şimdi derin bir nefes al.', 'You worked deeply; now breathe deeply.'],
    ['Dikkatini topladın ve zaman senin oldu.', 'You gathered your attention, and the time became yours.'],
    ['Bu seansta dünyayı biraz unuttun, kendini ise biraz daha buldun.', 'This session you forgot the world a little and found yourself a little more.'],
    ['Kor ruhu bu seans boyunca seninle birlikte büyüdü.', 'The ember spirit grew right along with you.'],
    ['Odak en değerli hediyendir ve onu kendine verdin.', 'Focus is your most precious gift, and you gave it to yourself.'],
    ['Seans tamam. Gözlerini dinlendir, uzaklara bak.', 'Session done. Rest your eyes, look into the distance.'],
    ['Böyle bir odakla her dağ aşılır.', 'With focus like this, any mountain can be crossed.'],
    ['Bir şeyi gerçekten yapmanın verdiği o huzur…', 'That calm that comes from truly doing something…'],
    ['Telefonu bıraktın, dünyayı susturdun, kazandın.', 'You put the phone down, quieted the world, and won.'],
    ['Zihnin bir kas gibi; bugün onu güzelce çalıştırdın.', 'Your mind is like a muscle; you gave it a good workout today.'],
    ['Odak ateşin harlı yanıyor.', 'Your focus fire is burning bright.'],
    ['Bu dakikalar, hayallerine doğru atılmış adımlardı.', 'Those minutes were steps toward your dreams.'],
    ['Kendini kaptırdın, harika! Şimdi biraz esne.', 'You got lost in it, wonderful! Now stretch a little.'],
    ['Sessiz bir zafer, ama gerçek bir zafer.', 'A quiet victory, but a real one.'],
    ['Konsantrasyonun etkileyici. Mola senin hakkın.', 'Impressive concentration. The break is all yours.'],
    ['Bir seans daha bitti; artık seni daha az şey bekliyor.', 'One more session done; less is waiting for you now.'],
    ['Zamanın kontrolü sendeydi. Bu güzel bir his.', 'You were in charge of your time. That’s a great feeling.'],
    ['Odaklanmak bir seçimdi ve sen doğru olanı seçtin.', 'Focusing was a choice, and you made the right one.'],
    ['Seans boyunca sabrın parladı.', 'Your patience shone throughout the session.'],
    ['Şimdi biraz su, biraz hareket. Sonra yine buradayız.', 'Now some water, some movement. Then we’re back.'],
    ['Bu tempoyla hayallerin çok yakın.', 'At this pace, your dreams are very close.'],
    ['Odak seansın, bugüne attığın güzel bir imza.', 'Your focus session is a lovely signature on today.'],
    ['Kendine ayırdığın bu zaman, en iyi yatırımın.', 'This time you gave yourself is your best investment.'],
  ],
  break: [
    ['Mola zamanı: omuzlarını gevşet, gözlerini kapat.', 'Break time: drop your shoulders, close your eyes.'],
    ['Bir bardak su iç; beynin de susadı.', 'Drink a glass of water; your brain is thirsty too.'],
    ['Ayağa kalk ve biraz esne. Vücudun sana teşekkür edecek.', 'Stand up and stretch. Your body will thank you.'],
    ['Pencereden dışarı bak; uzaklara bakmak gözlerine iyi gelir.', 'Look out the window; distant views rest your eyes.'],
    ['Bu molada ekranlardan uzak dur. Zihnin nefes alsın.', 'Stay away from screens this break. Let your mind breathe.'],
    ['Dört saniye nefes al, dört saniye tut, altı saniyede ver.', 'Breathe in for four, hold for four, out for six.'],
    ['Mola, çalışmanın düşmanı değil, en iyi arkadaşıdır.', 'A break isn’t the enemy of work; it’s its best friend.'],
    ['Sevdiğin bir şarkıyı aç ve sadece dinle.', 'Put on a song you love and just listen.'],
    ['Biraz yürü; fikirler yürürken gelir.', 'Take a little walk; ideas come while walking.'],
    ['Kendine küçük bir atıştırmalık hak ettin.', 'You’ve earned a little snack.'],
    ['Gözlerini kapat ve üç güzel şeyi düşün.', 'Close your eyes and think of three nice things.'],
    ['Mola bitince daha güçlü döneceksin.', 'You’ll come back stronger after the break.'],
    ['Bir bitkiyi sula ya da bir arkadaşına “nasılsın” yaz.', 'Water a plant or text a friend “how are you?”'],
    ['Boynunu yavaşça iki yana çevir. Merak etme, kimse bakmıyor.', 'Slowly turn your neck side to side. Don’t worry, no one’s watching.'],
    ['Biraz güneş, biraz hava; en iyi enerji içeceği.', 'A bit of sun, a bit of air; the best energy drink.'],
    ['Molada hiçbir şey yapmamak da bir beceridir.', 'Doing nothing on a break is a skill too.'],
    ['Ellerini ovuştur, avuçlarını gözlerine koy; sıcaklığı hisset.', 'Rub your hands together, cup them over your eyes, feel the warmth.'],
    ['Kor ruhu da dinleniyor. Sen de ona eşlik et.', 'The ember spirit is resting too. Keep it company.'],
    ['Mola demek, zihnin yeniden şarj olması demek.', 'A break means your mind is recharging.'],
    ['Bir sonraki seansa gülümseyerek dön.', 'Come back to the next session with a smile.'],
  ],
  level: [
    ['Seviye atladın {name}! Yolculuğun güzelleşiyor.', 'You levelled up, {name}! Your journey is getting better.'],
    ['Yeni bir seviye, yeni bir sen. Tebrikler!', 'A new level, a new you. Congratulations!'],
    ['Emeklerinin karşılığını alıyorsun. Bu daha başlangıç.', 'Your effort is paying off. This is only the beginning.'],
    ['Kahramanın gururla parlıyor.', 'Your hero is glowing with pride.'],
    ['Bir basamak daha yukarı! Manzara giderek güzelleşiyor.', 'One more step up! The view keeps getting better.'],
    ['Seviye atlamak tesadüf değil, her gün verdiğin emeğin sonucu.', 'Levelling up isn’t luck; it’s your everyday effort.'],
    ['Bu yükselişi hak ettin. Kutla!', 'You earned this rise. Celebrate!'],
    ['Hikâyende yeni bir bölüm başladı.', 'A new chapter of your story has begun.'],
    ['Dün hayal ettiğin seviyedesin. Yarın neyi hayal edeceksin?', 'You’re at the level you dreamed of yesterday. What will you dream tomorrow?'],
    ['Azmin yine kazandı!', 'Your persistence won again!'],
    ['Yükselmeye devam; tepede seni güzel bir şey bekliyor.', 'Keep climbing; something lovely waits at the top.'],
    ['Bu seviye, kararlılığının madalyası.', 'This level is a medal for your determination.'],
    ['Bir seviye daha! Kor ruhu sevinçten zıplıyor.', 'Another level! The ember spirit is jumping for joy.'],
    ['Gelişim genelde sessizdir ama bugün herkes duysun: seviye atladın!', 'Growth is usually quiet, but let everyone hear it today: you levelled up!'],
  ],
  streak: [
    ['Serin devam ediyor! İstikrar sessiz bir süper güçtür.', 'Your streak lives on! Consistency is a quiet superpower.'],
    ['Her gün biraz; işte büyük değişimin sırrı.', 'A little every day; that’s the secret of big change.'],
    ['Ateşin sönmüyor {name}. Ne güzel!', 'Your fire isn’t going out, {name}. How wonderful!'],
    ['Arka arkaya günler, sağlam alışkanlıklar inşa eder.', 'Day after day builds solid habits.'],
    ['Zinciri kırmadın. Kendinle gurur duy.', 'You didn’t break the chain. Be proud of yourself.'],
    ['Bu seri, kendine verdiğin sözleri tuttuğunu gösteriyor.', 'This streak shows you keep your promises to yourself.'],
    ['İstikrarın, yeteneğinden bile parlak.', 'Your consistency shines even brighter than your talent.'],
    ['Bir gün daha! Seri büyüdükçe sen de büyüyorsun.', 'One more day! As the streak grows, so do you.'],
    ['Alışkanlık, motivasyonun bittiği yerde seni taşır.', 'Habit carries you where motivation runs out.'],
    ['Kor her gün biraz daha harlanıyor.', 'The ember burns a little brighter every day.'],
    ['Bu seriyi kimse sana vermedi; sen kazandın.', 'No one gave you this streak; you earned it.'],
    ['Günler birbirine bağlandıkça hikâyen güçleniyor.', 'As the days link up, your story grows stronger.'],
    ['Yorulsan bile durmadın. Bu gerçek bir başarı.', 'You didn’t stop, even when tired. That’s real success.'],
    ['Serin, gelecekteki sene yazılmış bir sevgi mektubu gibi.', 'Your streak is like a love letter to your future self.'],
  ],
  login: [
    ['Tekrar hoş geldin {name}! Seni görmek güzel.', 'Welcome back, {name}! It’s good to see you.'],
    ['Yine buradasın. Bu bile başlı başına bir başarı.', 'You’re here again. That alone is an achievement.'],
    ['Bugünün hediyesi hazır. Ama en güzel hediye, gelmiş olman.', 'Today’s gift is ready. But the best gift is that you came.'],
    ['Her gün gelmek, kendine verebileceğin en güzel söz.', 'Showing up every day is the best promise you can make to yourself.'],
    ['Kor ruhu seni bekliyordu.', 'The ember spirit was waiting for you.'],
    ['Yeni bir gün, yeni bir hediye, yeni bir şans.', 'A new day, a new gift, a new chance.'],
    ['Geri dönmen, yolculuğun devam ettiğini gösteriyor.', 'Coming back shows the journey goes on.'],
    ['Merhaba {name}! Bugün neler yapalım?', 'Hello, {name}! What shall we do today?'],
    ['Sadece uğradın ama bu bile ateşi canlı tutar.', 'You just stopped by, but even that keeps the fire alive.'],
    ['Gelişin güzel; bugün de güzel olacak.', 'Your arrival is lovely; today will be lovely too.'],
    ['Bir gün daha birlikteyiz. Hazırsan başlayalım.', 'Another day together. Let’s begin when you’re ready.'],
    ['Seni gördüğüme sevindim. Kahramanın da öyle.', 'I’m happy to see you. So is your hero.'],
    ['Bugün kendine iyi davranacağın bir gün olsun.', 'Let today be a day you’re kind to yourself.'],
    ['Her ziyaret, ödül yolunda bir adım daha.', 'Every visit is one more step along the reward path.'],
    ['İstikrarın meyvelerini toplamaya devam!', 'Keep gathering the fruits of consistency!'],
    ['Kapıyı açtın, ışık içeri doldu. Hoş geldin.', 'You opened the door, and the light came in. Welcome.'],
    ['Bugün ne kadar yaparsan yap, gelmiş olman çok değerli.', 'However much you do today, showing up is precious.'],
    ['Hoş geldin! Yeni maceralar seni bekliyor.', 'Welcome! New adventures await.'],
  ],
  comeback: [
    ['Seni özledik {name}! Hiç sorun değil, kaldığın yerden devam.', 'We missed you, {name}! No problem at all; pick up where you left off.'],
    ['Ara vermek de yolculuğun bir parçası. Tekrar hoş geldin.', 'Taking a break is part of the journey too. Welcome back.'],
    ['Geri döndün ve en önemlisi bu.', 'You came back, and that’s what matters most.'],
    ['Hayat bazen yoğun olur. Önemli olan geri dönebilmek.', 'Life gets busy sometimes. What matters is coming back.'],
    ['Ateş biraz kısılmış olabilir ama kor hâlâ sıcak.', 'The fire may have dimmed, but the embers are still warm.'],
    ['Yeniden başlamak, hiç başlamamaktan her zaman güzel.', 'Starting again always beats never starting.'],
    ['Kendini suçlama; bugün yeni bir sayfa.', 'Don’t blame yourself; today is a new page.'],
    ['Kahramanın seni sabırla bekledi.', 'Your hero waited for you patiently.'],
    ['Küçük bir adımla geri dön; büyük adımlar zaten gelecek.', 'Come back with one small step; the big ones will follow.'],
    ['Ne kadar uzak kaldığın değil, döndüğün an önemli.', 'It’s not how long you were gone; it’s the moment you returned.'],
    ['Hoş geldin! Bugün tek bir görev yeter.', 'Welcome back! Just one quest is enough today.'],
    ['Mola uzun sürdü ama hikâye bitmedi.', 'The break was long, but the story isn’t over.'],
  ],
  allDone: [
    ['Bugünün tüm görevleri tamam! Şimdi gönül rahatlığıyla dinlen {name}.', 'All of today’s quests are done! Rest easy now, {name}.'],
    ['Liste bomboş, kalbin dopdolu.', 'Empty list, full heart.'],
    ['Her şeyi bitirdin. Bu his için çalıştın, tadını çıkar.', 'You finished everything. You worked for this feeling; enjoy it.'],
    ['Bugün kendi kahramanındın.', 'Today you were your own hero.'],
    ['Tamamlanmış bir gün, en güzel ödüldür.', 'A completed day is the best reward.'],
    ['Şimdi biraz kendine zaman ayır. Hak ettin.', 'Now take some time for yourself. You’ve earned it.'],
    ['Görevler bitti; şimdi hayatın tadını çıkarma zamanı.', 'Quests done; now it’s time to enjoy life.'],
    ['Bugün planladığın her şeyi yaptın. Bu nadir ve güzel bir şey.', 'You did everything you planned today. That’s rare and lovely.'],
    ['Kor ruhu bayram ediyor!', 'The ember spirit is celebrating!'],
    ['Yarın için enerjini korumak da bir görev; şimdi onu yap.', 'Saving energy for tomorrow is a quest too; do that now.'],
    ['Mükemmel bir gün. Biraz kendinle gurur duy.', 'A wonderful day. Be a little proud of yourself.'],
    ['Bugün dünyaya güzel bir iz bıraktın.', 'You left a lovely mark on the world today.'],
    ['Her şey tamam. Bir çay demleyelim mi?', 'Everything’s done. Shall we brew some tea?'],
    ['Bugünün kahramanı belli oldu: sen!', 'Today’s hero has been decided: you!'],
  ],
  goal: [
    ['Günlük odak hedefine ulaştın {name}! Harikasın.', 'You reached your daily focus goal, {name}! You’re amazing.'],
    ['Hedef tamam! Bugün zihnine iyi baktın.', 'Goal complete! You took good care of your mind today.'],
    ['Planladığın odağı yakaladın. Gerisi bonus.', 'You hit your planned focus. Everything else is a bonus.'],
    ['Kendine bir hedef koydun ve tuttun. Güven işte böyle büyür.', 'You set a goal and kept it. That’s how trust grows.'],
    ['Bugünün odak kotası doldu; artık keyfine bak.', 'Today’s focus quota is full; now enjoy yourself.'],
    ['Ateş tam istediğin kadar yandı.', 'The fire burned exactly as long as you wanted.'],
    ['Hedefine ulaşmak bir alışkanlığa dönüşüyor.', 'Reaching your goal is becoming a habit.'],
    ['Bugün sözünü tuttun. Bu çok değerli.', 'You kept your word today. That’s precious.'],
    ['Odak hedefi: başarıldı. Gülümse!', 'Focus goal: achieved. Smile!'],
    ['Bu tutarlılıkla yolun çok açık.', 'With this consistency, your road is wide open.'],
    ['Kendi çizdiğin çizgiyi geçtin. Tebrikler!', 'You crossed the line you drew for yourself. Congratulations!'],
    ['Bugünün odak madalyası senin.', 'Today’s focus medal is yours.'],
  ],
  low: [
    ['Bugün zor geçiyorsa, bu senin değerini değiştirmez.', 'If today is hard, it doesn’t change your worth.'],
    ['Kendine nazik ol; bugün sadece nefes almak bile yeterli.', 'Be gentle with yourself; today, just breathing is enough.'],
    ['Kötü günler de geçer, tıpkı bulutlar gibi.', 'Bad days pass, just like clouds.'],
    ['Ağlamak, kalbin kendini temizleme yoludur.', 'Crying is the heart’s way of clearing itself.'],
    ['Biriyle konuşmak iyi gelebilir. Yalnız değilsin.', 'Talking to someone can help. You’re not alone.'],
    ['Bugün sadece küçük bir şey yap: su iç, pencereyi aç ya da biraz uzan.', 'Do just one small thing today: drink water, open a window, or lie down for a bit.'],
    ['Hissettiklerin önemli; onları bastırmana gerek yok.', 'What you feel matters; you don’t have to push it down.'],
    ['En karanlık geceler bile sabaha varır.', 'Even the darkest nights reach morning.'],
    ['Kendine sıcak bir içecek hazırla ve bir battaniyeye sarın.', 'Make yourself a warm drink and wrap up in a blanket.'],
    ['Bugün ağırsa, yarın hafifleyebilir. Ona bir şans ver.', 'If today is heavy, tomorrow may be lighter. Give it a chance.'],
    ['Görevler bekleyebilir. Önce sen gelirsin.', 'Quests can wait. You come first.'],
    ['Yavaşlamak sorun değil; çiçekler de kışın dinlenir.', 'Slowing down is fine; flowers rest in winter too.'],
    ['Kendini olduğun gibi kabul etmek, iyileşmenin ilk adımıdır.', 'Accepting yourself as you are is the first step to healing.'],
    ['Bu duygu kalıcı değil. Sen ise çok güçlüsün.', 'This feeling isn’t permanent. And you are very strong.'],
    ['Sevdiğin bir şarkı, bir koku, bir anı… Birini kendine hediye et.', 'A favourite song, a scent, a memory… Gift yourself one.'],
    ['Buradayım. Bugün ne kadar az yaparsan yap, seninle gurur duyuyorum.', 'I’m here. However little you do today, I’m proud of you.'],
  ],
  high: [
    ['Enerjin harika! Bu ışığı etrafına da saç.', 'Your energy is great! Share this light around you.'],
    ['Bugün parlıyorsun {name}.', 'You’re glowing today, {name}.'],
    ['Bu güzel hissi bir yere not et; zor günlerde okursun.', 'Write this good feeling down somewhere; read it on hard days.'],
    ['Mutluluğun bulaşıcı. Birine güzel bir şey söyle!', 'Your happiness is contagious. Tell someone something nice!'],
    ['Böyle günler, hayatın hediyeleridir.', 'Days like this are gifts from life.'],
    ['Bu enerjiyle bugün harikalar yaratabilirsin.', 'With this energy, you can work wonders today.'],
    ['İyi hissetmeyi hak ediyorsun. Tadını çıkar.', 'You deserve to feel good. Enjoy it.'],
    ['Güzel bir gün! Bu anı kalbine kaydet.', 'A lovely day! Save this moment in your heart.'],
    ['Gülümsemen bugün güneşle yarışıyor.', 'Your smile is competing with the sun today.'],
    ['Bu güzel ruh hâline bir görev ekle; uçarak bitecek.', 'Add a quest to this good mood; you’ll fly through it.'],
  ],
};

export const QUOTE_COUNT = Object.values(QUOTES).reduce((n, list) => n + list.length, 0);
